Drop table if exists US_Trip_Adv_Reviews cascade;
CREATE TABLE US_Trip_Adv_Reviews (
   Museum_ID  int   NOT NULL,
   Museum_Name varchar(356)   NOT NULL,
   Museum_Type_ID int  ,
   Full_Address  varchar(356)  ,
   Street_Add_PhyLoc varchar(356)  ,
   City_PhyLoc varchar(356)   ,
   State_PhyLoc varchar(2)   ,
   Zip_PhyLoc varchar(10)  ,
   Phone_Number varchar(64) ,
   Latitude decimal ,
   Longitude decimal  ,
   FIPS_County int ,
   Rank	decimal   ,
   Rating	decimal   ,
   ReviewCount decimal ,
   Parent_Museum_ID bigint,
   FIPS_County_new int 	,
   PRIMARY KEY (Museum_ID));